---
title: <center>Frequently Asked Questions
output: html_document
---
----
The Ocean Health Index was developed to measure the benefits that people recieve from the ocean now and into the future. 
The index was originally developed to measure [global ocean health](http://ohi-science.org/ohi-global). Since then, regional assessments have been done in twenty regions to meet local needs to track sustainable ocean use. 
<br><br>


## Why is this study being done?

There is a need to assess and track the health of our natural environment and chart a path forward to increase economic opportunities and human wellbeing while sustainably managing these critical resources.
<br><br>


## What is the purpose of this project?

To develop shared metrics for measuring progress toward sustainable economic growth and ocean health through:

1. Building a coalition for sustainable ocean management, 
2. Collaborating with coastal stakeholders, natural resource managers, scientific experts, and communities, 
3. Using objective scientific data to inform decision-making, and
4. Monitor ocean health through time using the OHI as a repeatable tool.

<br><br>


## What is the ultimate goal of this project?
Enable our region, including, community stakeholders, the corporate and finance sectors and non-profit organizations to prioritize investments and policy decisions that affect the sustainability of our economic and ocean health.
<br><br>


## How far along is this project?
We are in the development and planning stages. Stakeholder engagement and outreach is continuing and we are working with local advisors and experts to facilitate the development of the Ocean Health Index here. 
