-----

# Provenance

``` {r provenance_info, echo = FALSE, message = FALSE, warning = FALSE}
### NOTE: To work properly, prov.R needs to be sourced in parent document; and
###   'this_script_file' needs to be set (in the parent) to the filename
###   of the parent document.

message('call script_prov')
x <- script_prov(prov_parent_script_file) 
```

- _Run ID: `r x$run_id`; run tag: "`r x$run_tag`"_
- _Run elapsed time: `r x$elapsed_time` seconds; run memory usage: `r x$memory_use` MB_
- _System info: `r x$msg_sys`_
- _Session info_
    - _`r x$msg_ses`_
    - _`r x$msg_base_pkgs`_
    - _`r x$msg_att_pkgs`_
    
``` {r provenance_plot,  echo = FALSE, message = FALSE}

# DT::datatable(script_track[ , 1:9],
#               caption = 'Provenance summary for this run:',
#               rownames = FALSE,
#               class = 'stripe hover compact',
#               options  = list(dom = 'tp'))

message('call plot_prov')

plot_prov(script_track)

```

``` {r provenance_table,  echo = FALSE, message = FALSE}

# DT::datatable(script_track[ , 1:9],
#               caption = 'Provenance summary for this run:',
#               rownames = FALSE,
#               class = 'stripe hover compact',
#               options  = list(dom = 'tp'))

message('create the data table')

prov_tbl <- script_track %>% #[ , 1:10] %>%
  mutate(commit_url = str_replace(commit_url, 'Previous commit: ', ''),
         commit_url = ifelse(commit_url == 'no version control info found', NA, commit_url),
         commit_id  = ifelse(is.na(commit_url), NA,
                             sprintf('[%s](%s)', str_sub(commit_url, -6, -1), commit_url)))
                             # sprintf('<a href = %s>%s</a>', commit_url, str_sub(commit_url, -6, -1))))

run_id   <- first(prov_tbl$run_id)
run_tag  <- first(prov_tbl$run_tag)
run_date <- first(prov_tbl$run_date)

prov_tbl1 <- prov_tbl %>%
  mutate(file_name = basename(as.character(file_loc)),
         file_dir  = dirname(as.character(file_loc))) %>%
  # dplyr::select(file_name, file_dir, filetype, uncomm_chgs = uncommitted_changes, commit_id)
  dplyr::select(file_name, file_dir, filetype, 
#   parent_fn, rdf_subject, rdf_object, rdf_predicate,
    uncomm_chgs = uncommitted_changes, commit_id)


knitr::kable(prov_tbl1 %>% 
               arrange(filetype, file_name),
             caption = sprintf('Provenance summary for run %s: %s (%s)', run_id, run_tag, run_date),             
             # row.names = FALSE,
             class = 'stripe hover compact')

```

