---
title: 'OHIBC: Howe Sound summary'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ohibc/src/templates/ohibc_hdr1.html'
  pdf_document:
    toc: true
---

``` {r setup, echo = FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'Figs/',
                      echo = FALSE, message = FALSE, warning = FALSE)

source('~/github/ohibc/src/R/common.R')  ### an OHIBC specific version of common.R;
  ### includes library(tidyverse); library(stringr)

dir_git     <- '~/github/ohibc'
dir_spatial <- file.path(dir_git, 'prep/spatial')  ### github: general buffer region shapefiles
dir_anx     <- file.path(dir_M, 'git-annex/bcprep')

### goal specific folders and info
scenario_rgn <- 'regionHoweSound'
dir_scenario <- file.path(dir_git, scenario_rgn)
dir_scenario_anx <- file.path(dir_anx, scenario_rgn)

### provenance tracking
library(provRmd); prov_setup()

### support scripts
source(file.path('~/github/ohibc/src/R/map_scores.R'))
  ### score plotting scripts
source(file.path(dir_git, 'src/R/rast_tools.R')) 
  ### raster plotting and analyzing scripts

### set up the default BC projection to be BC Albers
p4s_bcalb <- c('bcalb' = '+init=epsg:3005')

```

# Summary

Gather results from OHI Howe Sound goals into a single report; create visuals for each goal

***

# Gather scores for all Howe Sound goals

``` {r get_all_scores}


get_scores <- function(layer) { # layer <- hs_layers[1, ]
  dir_goal <- file.path(layer$base_dir, layer$dir, layer$scenario, 'output')

  st_df <- read_csv(file.path(dir_goal, layer$status_fn))
  
  ### add rgn_id and year if not present
  if(!('rgn_id' %in% names(st_df))) st_df$rgn_id <- 1
  if(!('year'   %in% names(st_df))) st_df$year   <- NA
  
  ### rename status column to score
  names(st_df)[names(st_df) == layer$status] <- 'score'
  
  ### select and add dimension column
  st_df <- st_df %>%
    select(rgn_id, score, year) %>%
    mutate(score = ifelse(is.na(score), NA, score/layer$layer_scale)) %>% ### to account for 0-1 vs 0-100
    mutate(dimension = 'status')
  
  ### gather trend info
  tr_df <- read_csv(file.path(dir_goal, layer$trend_fn))
  
  ### add rgn_id and year if not present
  if(!('rgn_id' %in% names(tr_df))) tr_df$rgn_id <- 1
  if(!('year'   %in% names(tr_df))) tr_df$year   <- NA
  
  ### rename status column to score
  names(tr_df)[names(tr_df) == layer$trend] <- 'score'
  
  ### select and dimension column
  tr_df <- tr_df %>%
    select(rgn_id, score, year) %>%
    mutate(dimension = 'trend')
  
  score_df <- bind_rows(st_df, tr_df) %>%
    mutate(goal = layer$goal)
  
}

hs_layers <- read_csv(file.path(dir_scenario, 'layers.csv')) %>%
  filter(layer_include == TRUE)

### convert layers dataframe into a list of df rows; this allows
### lapply to work on each as a dataframe instead of atomic vector
hs_layers_list <- split(hs_layers, seq(nrow(hs_layers)))

scores <- lapply(hs_layers_list, get_scores) %>%
  bind_rows()

write_csv(scores, file.path(dir_scenario, 'scores.csv'))

scores_print <- scores %>%
  filter(is.na(year) | year == 2016) %>%
  filter(dimension == 'status') %>%
  select(-year, -rgn_id) %>%
  distinct()

```

`r knitr::kable(scores_print)`

# Create flower plot

``` {r create_flower_plot}

layers <- read_csv(file.path(dir_scenario, 'layers.csv')) %>%
  filter(layer_include)

status_df <- read_csv(file.path(dir_scenario, 'scores.csv')) %>%
  mutate(score = score * 100) %>%
  filter(is.na(year) | year == 2016) %>%
  filter(dimension == 'status') %>%
  select(-year, -rgn_id) %>%
  distinct() %>%
  inner_join(layers %>% select(goal, weight), by = 'goal')


goal_labels <- status_df %>%
  left_join(read_csv(file.path(dir_scenario, 'goal_names.csv')),
            by = 'goal') %>%
  mutate(goal_label = str_replace(goal_label, ' ', '\n'),
         goal_label = paste(goal_label, round(score), sep = '\n')) %>%
  select(goal, goal_label)

# PlotFlower = function (lengths, widths, labels, disk=0.5, max.length,
#                   center=NULL, main=NULL, fill.col=NULL, plot.outline=TRUE,
#                   label.offset=0.15, xlim=c(-1.2, 1.2), ylim=c(-1.2, 1.2), uin=NULL,
#                   tol=0.04, cex=1, bty="n", lty=1, 
#                   label.col='black', label.font=3, label.cex=NULL, ...)
# ohicore::PlotFlower(lengths = status_df$score, widths = status_df$weight, labels = status_df$goal, max.length = 1, plot.outline=TRUE)

source(file.path(dir_scenario, 'plot_flower.R'))
plot_flower(status_df,
            # score_ref   = 1,    ### scale from 0-1 or 0-100? default is 0-100
            outline     = TRUE,   ### show the outer borders; default is yes indeedy
            filename    = file.path(dir_scenario, 'howe_sound_flower.png'),
            center_text = NULL, ### pass it a number or label; default is blank
            center_score = TRUE, ### overridden if center_text != NULL
            goal_labels = goal_labels, ### show goal labels? a df swaps in new labels
            incl_legend = TRUE, ### show the legend? FALSE hides the legend
            show_plot   = TRUE)


```


``` {r create_diff_flower_plot, eval = FALSE}

layers <- read_csv(file.path(dir_scenario, 'layers.csv'))

diff_df <- read_csv(file.path(dir_scenario, 'scores.csv')) %>%
  filter(dimension == 'status') %>%
  left_join(layers %>% select(goal, weight), by = 'goal') %>%
  bind_rows(.[1, ] %>%
              mutate(goal = 'foo', score = NA, weight = .3)) %>%
  rowwise() %>%
  mutate(score_old = runif(1, .5, 1)) %>%
  rename(score_new = score)

source(file.path(dir_scenario, 'plot_flower_diff.R'))
plot_flower_diff(diff_df,
                 score_cols  = c('score_old', 'score_new'),
                 score_ref   = 1,    ### scale from 0-1 or 0-100? default is 0-100
                 outline     = TRUE,   ### show the outer borders; default is yes indeedy
                 filename    = file.path(dir_scenario, 'howe_sound_diff_flower.png'),
                 center_text = NULL, ### pass it a number or label; default is blank
                 incl_center_diff = TRUE, ### overridden if center_text != NULL
                 incl_goal_labels = TRUE, ### show goal labels? FALSE hides the goal labels
                 incl_legend = TRUE, ### show the legend? FALSE hides the legend
                 show_plot   = TRUE)

```

``` {r create_flower_plot_canada}

layers <- data.frame(goal   = c( 'AO',  'BD', 'HAB', 'SPP',  'CP',  'CS',  'CW',  'FP', 'FIS',  'MAR',  'LE', 'LIV', 'ECO',  'NP',  'SP', 'ICO',  'LSP',  'TR'),
                     weight = c(   1,     0,   0.5,   0.5,     1,     1,     1,     0,   0.5,    0.5,     0,   0.5,   0.5,     1,     0,   0.5,    0.5,     1))

status_df <- read_csv('~/github/ohi-global/eez2016/scores.csv') %>%
  filter(region_id == 218) %>%
  filter(dimension == 'status') %>%
  select(-region_id) %>%
  distinct() %>%
  left_join(layers %>% select(goal, weight), by = 'goal') %>%
  mutate(goal = factor(goal, levels = layers$goal)) %>%
  arrange(goal)

# PlotFlower = function (lengths, widths, labels, disk=0.5, max.length,
#                   center=NULL, main=NULL, fill.col=NULL, plot.outline=TRUE,
#                   label.offset=0.15, xlim=c(-1.2, 1.2), ylim=c(-1.2, 1.2), uin=NULL,
#                   tol=0.04, cex=1, bty="n", lty=1, 
#                   label.col='black', label.font=3, label.cex=NULL, ...)
# ohicore::PlotFlower(lengths = status_df$score, widths = status_df$weight, labels = status_df$goal, max.length = 1, plot.outline=TRUE)

source(file.path(dir_scenario, 'plot_flower.R'))
plot_flower(status_df,
            score_ref   = 100,    ### scale from 0-1 or 0-100? default is 0-100
            outline     = TRUE,   ### show the outer borders; default is yes indeedy
            filename    = file.path(dir_scenario, 'canada_flower.png'),
            center_text = NULL, ### pass it a number or label; default is blank
            incl_center_score = TRUE, ### overridden if center_text != NULL
            incl_goal_labels  = TRUE, ### show goal labels? FALSE hides the goal labels
            incl_legend = TRUE, ### show the legend? FALSE hides the legend
            show_plot   = TRUE)


```

***

# Citation information  
[citation information: include if these data will have their own specific citation.]

***

``` {r prov_footer, results = 'asis'}
prov_wrapup()
```

