---
title: "OHIBC: data_prep_lsp.Rmd"
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output: 
  html_document:
    toc: true
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes: 
      in_header: '~/github/ohibc/src/templates/ohibc_hdr1.html'
  pdf_document:
    toc: true
---

``` {r setup, echo = FALSE, eval = TRUE, message = FALSE, warning = FALSE}
library(sp)        # the classes and methods that make up spatial ops in R
# library(gdalUtils) # for gdal_rasterize() function
library(maptools)  # tools for reading and manipulating spatial objects
library(rgeos)
library(rgdal)
library(raster)
library(cleangeo)


dir_git  <- '~/github/ohibc'         ### set wd to work in Github OHIBC location
source(file.path(dir_git, 'src/R/common.R'))  ### an OHIBC specific version of common.R

dir_anx <- file.path(dir_neptune_data, 'git-annex/bcprep') ### git-annex: goal-specific large files
dir_rgn <- file.path(dir_git, 'prep/regions')       ### github: general buffer region shapefiles
dir_rst <- file.path(dir_anx, 'lsp/spatial')  ### git-annex: goal-specific raster files
dir_lsp <- file.path(dir_git, 'prep/lsp')
source(file.path(dir_lsp, 'R/lsp_fxns.R'))

### provenance tracking
source('~/github/ohibc/src/R/prov.R')      
  ### Provenance tracking functions: must source at start to initialize prov_track
dir_prov <- file.path(dir_lsp, 'prov') 
  ### set a provenance folder for this script
this_script_file <- file.path(dir_lsp, 'data_prep_lsp.Rmd') 
  ### can't recognize the current script name on its own :(
prov_run_tag <- 'standard run'


### set up the default BC projection to be BC Albers
p4s_bcalb <- '+proj=aea +lat_1=50 +lat_2=58.5 +lat_0=45 +lon_0=-126 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs +ellps=GRS80 +towgs84=0,0,0'
```

# Pressures layer preparation

List of pressures in progress can be found at: https://docs.google.com/spreadsheets/d/1w7-XwkE3W8mts_96dWKHp0cgWyx8iasb4b7H9l-qEJY/edit#gid=993416664

## Layers data sources:

The following layers will likely be taken from global cumulative impacts layers directly.  Dan's work on cumulative impacts over time will allow us to understand these layers on a year-to-year basis.

* SST  
* pH  
* UV   
* Sea level rise

The following layers may be taken from global CHI although local activities may be used to modify them? or new methods entirely?

* Chemicals
* Nutrients
* HD intertidal trampling
* HD intertidal construction

The following layers may use similar techniques to CHI for California Current or from BC CHI (Ban 2010/SeaSketch)

* Noise pollution
* Light pollution

The following layers are likely to be dependent on data from DFO:

* Commercial High bycatch  
* Commercial Low bycatch    
* Artisanal Low bycatch   
* Artisanal high bycatch (e.g., dynamite fishing) 
* Targeted harvest 
* Stock status as pressure on AO?
* Recreational non-FN?
* Genetic Escapes   
* Aquaculture Nutrients - finfish and shellfish
* Disease and parasites
* HD subtidal soft bottom  
* HD subtidal hard bottom 

# Preparing global pressures layers

1. Import global raster (degrees? equal-area projection?)
2. Clip global raster to extents appropriate to BC region
3. Reproject raster to BC Albers(? necessary? or leave native)

??? where are the raster data layers available
??? how should we incorporate the time-dependence via Dan's work
