---
title: "IUCN vs NatureServe conservation status ranks"
output: 
  html_document:
    toc: true
    theme: spacelab
    highlight: haddock
---

### NatureServe conservation status rank codes and definitions (for global level) 

*from http://www.natureserve.org/conservation-tools/conservation-status-assessment*

| IUCN analog? | NatureServe Global Rank | Definition |
| :----------: | :---------------------: | :--------- |
| EX           | GX	                     | Presumed Extinct (species)/Eliminated (ecological communities and systems) — Species not located despite intensive searches and virtually no likelihood of rediscovery. Ecological community or system eliminated throughout its range, with no restoration potential. |
| EX?          | GH	                     | Possibly Extinct (species)/ Eliminated (ecological communities and systems) — Known from only historical occurrences but still some hope of rediscovery. There is evidence that the species may be extinct or the ecosystem may be eliminated throughout its range, but not enough to state this with certainty. |
| CR           | G1	                     | Critically Imperiled—At very high risk of extinction due to extreme rarity (often 5 or fewer populations), very steep declines, or other factors. |
| EN           | G2                       | Imperiled—At high risk of extinction or elimination due to very restricted range, very few populations, steep declines, or other factors. |
| VU           | G3	                     | Vulnerable—At moderate risk of extinction or elimination due to a restricted range, relatively few populations, recent and widespread declines, or other factors. |
| NT           | G4	                     | Apparently Secure—Uncommon but not rare; some cause for long-term concern due to declines or other factors.
| LC           | G5	                     | Secure—Common; widespread and abundant. | 

### Additional codes for provincial/state level 

*from http://explorer.natureserve.org/nsranks.htm*

| IUCN analog? | NatureServe Provincial Rank | Definition |
| :----------: | :-------------------------: | :--------- |
| NA           | NNR/SNR                     | Unranked—Nation or state/province conservation status not yet assessed. |
| NA           | NU/SU                       | Unrankable—Currently unrankable due to lack of information or due to substantially conflicting information about status or trends. |
| NA           | NNA/SNA                     | Not Applicable —A conservation status rank is not applicable because the species is not a suitable target for conservation activities. |
| mean value   | N#N#/S#S#                   | Range Rank —A numeric range rank (e.g., S2S3) is used to indicate any range of uncertainty about the status of the species or community. Ranges cannot skip more than one rank (e.g., SU is used rather than S1S4). |
| NA           | Not Provided                | Species is known to occur in this nation or state/province. Contact the relevant natural heritage program for assigned conservation status. Contact information for individual natural heritage programs is available at http://www.natureserve.org/natureserve-network. |

**Breeding Status Qualifiers**

| Qualifier | Definition |
| :-------: | :--------- |
| B         | Breeding—Conservation status refers to the breeding population of the species in the nation or state/province.
| N         | Nonbreeding—Conservation status refers to the non-breeding population of the species in the nation or state/province.
| M         | Migrant—Migrant species occurring regularly on migration at particular staging areas or concentration spots where the species might warrant conservation attention. Conservation status refers to the aggregating transient population of the species in the nation or state/province.

``` {r compare Natureserve to IUCN, eval = FALSE}
### run this after 'append bc scores' chunk in data_prep_spp.Rmd
  spp_natureserve <- spp_all1 %>%
    filter(!is.na(status_gl_score) | !is.na(status_pr_score)) %>%
    filter(!str_detect(spatial_source, 'subpop')) %>%
    filter(!str_detect(spatial_source, 'alias')) %>%
    select(sciname, am_sid, iucn_sid, spatial_source, popn_category, category_score, status_gl_score, status_gl, status_pr_score, status_pr)
  
  ns_v_iucn1 <- ggplot(data = spp_natureserve, aes(x = category_score, y = status_gl_score)) +
    geom_point(position = position_jitter(w = 0.03, h = 0.03))
  ns_v_iucn1
  qwer <- lm(category_score ~ status_gl_score, data = spp_natureserve)
  summary(qwer)
  # Coefficients:   Estimate Std. Error t value Pr(>|t|)    
  # (Intercept)      0.01565    0.01744   0.897    0.372    
  # status_gl_score  0.72998    0.08775   8.319  3.9e-13 ***
  # 
  # Multiple R-squared:  0.4019,  Adjusted R-squared:  0.3961 
}