# Assemble the habitat layers.

- Group by "priority"
- Check for overlaps in this priority category
- Assemble "priority" layers
- Build up from lowest priority to highest priority.

Priority:
1: layer based on biological habitat indicators
2: layer based on structure as proxy
3: layer based on benthic type as proxy

``` {r group_rasters_by_priority, echo = FALSE}
hab_lyrs <- read_csv(file.path(dir_hab, 'pressures_hab_layers.csv'))

lyr_names_df <- hab_lyrs %>%
  select(category, priority, layer_id) %>%
  filter(!is.na(priority)) %>%
  unique

pri_lyr_list <- list() ### a list of layer stacks for each priority level
for(i in 1:max(lyr_names_df$priority)) { # i = 1
  tmp_layer_list <- list() ### a list of rasters temporarily stored for priority level i
  tmp_lyr_names <- lyr_names_df %>% filter(priority == i)
  for(j in tmp_lyr_names$category) { # j = tmp_lyr_names$category[i]
    ### create raster name from category name
    tmp_layer_name <- paste('hab_lyr_', str_replace_all(j, ' ', '_'), '.tif', sep = '')
    tmp_layer_id   <- tmp_lyr_names$layer_id[tmp_lyr_names$category == j]
    ### load raster for this category
    message(sprintf('Loading priority %s layer #%s: %s', i, tmp_layer_id, tmp_layer_name))

    tmp_layer_list[[j]] <- raster(file.path(dir_rast, tmp_layer_name))
  }
  names(tmp_layer_list) <- tmp_lyr_names[i]$category
  pri_lyr_list[[i]] <- stack(tmp_layer_list)
  names(pri_lyr_list)[i] <- i
}
```

``` {r check_priority_layers_for_overlap, echo = FALSE, eval = TRUE}

for (i in names(pri_lyr_list)) { # i = names(pri_lyr_list)[1]
  x <- getValues(pri_lyr_list[[i]])
  conflicts <- x[rowSums(!is.na(x)) > 1, ] 
  conflicts <- conflicts[ , colSums(!is.na(conflicts)) > 1] %>%
    as.data.frame() %>%
    unique()
  message('Priority ', i, ': Conflicts detected: ', nrow(conflicts))
  if(nrow(conflicts) > 0) {
    conflict_table <- knitr::kable(conflicts, caption = i)
    print(conflict_table)
  }
}
```

``` {r assemble_priority_layers, echo = FALSE}
### For now, just choose the cell value by the minimum non-NA value.
pri_lyr <- list()
for (i in names(pri_lyr_list)) { # i = names(pri_lyr_list)[1]
  pri_lyr[[i]] <- calc(pri_lyr_list[[i]], fun = min, na.rm = TRUE)
}
rast_hab_total <- pri_lyr[[3]]
values(rast_hab_total)[!is.na(values(pri_lyr[[2]]))] <- 
  values(pri_lyr[[2]])[!is.na(values(pri_lyr[[2]]))]
values(rast_hab_total)[!is.na(values(pri_lyr[[1]]))] <- 
  values(pri_lyr[[1]])[!is.na(values(pri_lyr[[1]]))]

plot(rast_hab_total)

writeRaster(rast_hab_total, file.path(dir_rast, 'hab_total.tif'))
```

