---
title: 'OHIBC: Regress observed vs. predicted status'
author: "*Compiled on `r date()` by `r Sys.info()['user']`*"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 3
    toc_float: yes
    number_sections: true
    theme: cerulean
    highlight: haddock
    includes:
      in_header: '~/github/ohibc/src/templates/ohibc_hdr1.html'
  pdf_document:
    toc: true
---

``` {r setup, echo = TRUE, message = FALSE, warning = FALSE}

knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'Figs/',
                      echo = TRUE, message = FALSE, warning = FALSE)

source('https://raw.githubusercontent.com/oharac/src/master/R/common.R')

dir_ohibc  <- '~/github/ohibc'
dir_calc   <- file.path(dir_ohibc, 'calc_ohibc')
dir_master <- file.path(dir_calc, 'master')

source(file.path(dir_calc, 'calc_scores_fxns.R'))

### provenance tracking
# library(provRmd); prov_setup()

```


# Regress predicted vs observed status

Goal by goal, regress likely future state in time $t$ against observed status in time $t + 5$.  Fixed effects on region as well as no fixed effects.

Because the regression of resilience on pressures is so weak, we won't worry about components in this regression - just the calculated LFS vs. the observed status.

``` {r}

scores <- read_csv(file.path(dir_calc, 'scores_all.csv')) %>%
  filter(region_id != 0) %>%
  spread(dimension, score) %>%
  mutate(pred_status = lag(future, 5),
         obs_status = status) %>%
  filter(!is.na(pred_status) & !is.na(obs_status)) %>%
  left_join(get_rgn_names(), by = c('region_id' = 'rgn_id'))

lfs_plot <- ggplot(scores, aes(x = pred_status, y = obs_status, color = goal)) +
  geom_point() +
  geom_abline(yintercept = 0, slope = 1) +
  geom_smooth(method = 'lm', se = FALSE)

print(lfs_plot)

goals <- scores$goal %>% unique()

collect_df <- data.frame()

for(goalname in goals) { ### goalname <- goals[1]
  tmp_df <- scores %>%
    filter(goal == goalname)
  
  mdl_rgn_yr_fe <- lm(obs_status ~ pred_status + factor(rgn_name) + factor(year), data = tmp_df)
  
  regr_future <- mdl_rgn_yr_fe %>%
    broom::tidy() %>%
    mutate(goal  = goalname,
           n_obs = nrow(tmp_df),
           years = length(tmp_df$year %>% unique()),
           adj_r_squared = summary(mdl_rgn_yr_fe)$adj.r.squared,
           aic = AIC(mdl_rgn_yr_fe))
  
  collect_df <- bind_rows(collect_df, regr_future)

}

write_csv(collect_df, 'int/lfs_status_fe.csv')

```


```{r}

lfs_mdl <- read_csv('int/lfs_status_fe.csv') %>%
  mutate(est_text = formatC(round(estimate, 4), digits = 4, format = 'f'),
         est_text = case_when(p.value < .001 ~ paste0(est_text, '***'),
                              p.value <  .01 ~ paste0(est_text, '**'),
                              p.value <  .05 ~ paste0(est_text, '*'),
                              p.value <  .10 ~ paste0(est_text, '°'),
                              TRUE ~ est_text)) %>%
  select(goal, adj_r_squared, aic, term, est_text) %>%
  spread(term, est_text) %>%
  clean_df_names()

write_csv(lfs_mdl, 'int/lfs_status_fe_formatted_p.csv')

DT::datatable(lfs_mdl %>% mutate_if(is.numeric, ~ round(., 4)))

```
