### Goal Description

Marine resources in British Columbia play a critical role in the cultural, ceremonial, and material well-being of coastal First Nations communities.  Ensuring access to healthy resources for food, social, and ceremonial (FSC) purposes remains a high priority for coastal First Nations (XXX Ref? CCIRA, others?) (also responsibility of DFO/Province in treaties?).  

The First Nations Resource Access Opportunity (AO) goal examines access, irrespective of exploitation, of four marine resources of broad FSC importance to First Nations communities across the British Columbia coast:  salmon, shellfish beds, herring spawn-on-kelp, and access to commercial fisheries.  

### Model  

The status model for the AO goal examines each of four components separately and averages scores for the overall status.  

* As a proxy for fisheries access, we compare the proportion of commercial fishing licenses within each region allocated specifically for aboriginal uses (from the DFO) to the proportion of the region's population living in First Nations communities (based upon census districts).  A score of 100 in this component indicates the proportion of FN-allocated licenses meets or exceeds the proportion of FN population, or 15%, whichever is greater. _(should that 15% be based on something other than "seemed like a good idea at the time" - e.g. FN vs total pop in BC?)_
* Shellfish gardens provide a traditional source of nutrition, but contamination events potentially restrict access.  For this component, we determined the number of contamination-related shellfish closure days in each fishery management subarea, and calculated an area-weighted mean number of closure-free days throughout each region.  A score of 100 in this component indicates no closures due to contamination in the region.
* Using herring spawn index data we estimated the mean density of herring spawn available in OHIBC region, applying a rolling three-year mean to smooth typical interannual variations.  A score of 100 in this component indicates a smoothed herring spawn index value that meets or exceeds the mean value across a 20-year reference period from 1940-1960, prior to a crash in herring stocks in the 1960s.
* Salmon (TBD) mean stock health of a few key salmon fisheries: healthy stocks indicate good access for FN into the future

### Reference points 

...




