### Goal Description

This goal aims to assess the amount of protection provided by marine and coastal habitats against flooding and erosion to coastal areas that people value, both inhabited (homes and other structures) and uninhabited (parks, special places, etc.). A score of 100 would indicate that these habitats are all still intact or have been restored to their reference conditions.

### Model & Data 

The CPP model is based on the relative health of the habitats that provide shoreline protection, weighted by their area and protectiveness rank (Halpern 2015 final) and exposure. For this analysis we include saltmarsh habitat and coastal forests (wetland area and forested area along coasts, below 5 m elevation).  We elected not to include seagrasses at this time due to lack of reliable time series data on seagrass extent or health.  Condition of each habitat was calculated based on coverage area, using land use rasters from 1990, 2000, and 2010 to determine change.  Rank weights for the protective ability of each habitat (Rk) come from previous work48 that ranks mangroves, corals and sea ice as 4, salt marshes as 3, and seagrasses as 1 (higher values are better) (Halpern 2012 ***InVEST MODEL DOCUMENTATION/REFS?***). Coastal forests are treated as analogous to mangroves for protective ability.

### Reference points 

We use a temporal reference point (ie. coverage data of a historical point) for each type of habitat. For both saltmarsh and coastal forest extent, we consider 1990 as a baseline due to limited data availability prior to that.  <!-- for saltmarsh in Howe Sound, we modify that baseline using historical records that indicate an average 30% loss relative to historical extents.  This is not currently implemented for OHIBC.-->

