### Goal Description

Sense of Place goal tries to capture the aspects of the coastal and marine system that people value as part of their cultural identity. This definition includes people living near the ocean and those who live far from it but still derive a sense of identity or value from knowing particular places or species exist. The sub-goal of Lasting Special Places focuses on those geographic locations that hold particular value for aesthetic, spiritual, cultural, recreational or existence reasons, and assesses how well they are protected. A score of 100 means the species and places important for cultural identity are protected and conserved.

### Model  

The model measures the percentage of coastal marine protected area and protected coastline in each country, against a reference percentage. We include protected areas within coastal waters (within 3nmi of shore) for marine special places assuming that sense of place is limited to areas accessible to or visible from the shoreline.  For land-based special places, we focused on coastal sub-watersheds as a way to increase the likelihood that the area being protected by terrestrial parks is connected to the marine system in some way.  We counted protection status using a variety of sources, including the World Database of Protected Areas, British Columbia parks and protected areas, tribal parks, and MaPP Special Management Zones related to historical, traditional, and cultural importance.

### Reference points 

The reference target (as a percentage of the total area) is 30% of coastal waters under protection and 30% of coastal sub-watersheds protected.

