### Goal Description

Mariculture measures the ability to reach the highest levels of seafood gained from farm-raised facilities without damaging the ocean’s ability to provide fish sustainably now and in the future. Higher scores reflect high food provisioning in a sustainable manner, while not compromising the water quality in the farmed area and not relying on wild populations to feed or replenish the cultivated species. A score of 100 means that a region is sustainably harvesting the greatest amount of farmed seafood possible based on its own potential.

### Model

The MAR model compares the aquaculture harvest within a region to its total harvest potential, for both finfish and bivalve aquaculture.  Using aquaculture growth potential index data from XXX Gentry et al XXX, we determined a mean harvest potential for finfish and bivalves for each region, in tonnes/km^2.  Comparing this potential to the designated aquaculture tenures for finfish and bivalves provides a measure of the total harvest potential, in tonnes, for each region.

### Reference points 

For both finfish and shellfish, a score of 100 reflects a harvest equal to the lower bound on potential calculated from (mean - 1 sd) of the growth potential index: $potential_{LowerBound} = P(\Phi' - \sigma_{\Phi'})$.  For shellfish, any harvest above this value earns a score of 100, since exceeding this value is unlikely to have ecological impacts, and is unlikely in any case.  For finfish, harvest between the lower bound on potential up to the mean potential ($potential_{mean} = P(\Phi')$) is scored as 100, beyond which score drops to zero at twice the mean potential ($potential_{max} = 2.0P(\Phi')$), as unsustainable stocking densities increase incidence of disease, parasites, and water pollution.


