### Goal Description

People value biodiversity in particular for its existence value. The risk of species extinction generates great emotional and moral concern for many people. As such, Biodiversity goal assesses the conservation status of species based on the best available global data. This sub-goal of Species assesses the health of all marine species present in a region, including endangered species and species in relatively good conditions.

### Model & Data 

The Species model measures the average threat status, defined by COSEWIC province-level threat assessments where available and IUCN Red List threat assessments elsewhere, of species in each region, weighted by each species' area of distribution within the region.

<!--
Species distributions come from three sources: 

- marine species from IUCN Red List of Threatened Species spatial data (IUCN 2016).
- seabirds using distributions from Birdlife International (BirdLife International and NatureServe 2016). 
- AquaMaps where neither IUCN nor BirdLife International distributions were available (Kaschner et al. 2016).

Species extinction risks come from 
-->

### Reference points 

The upper reference point for the Species sub-goal is to have all species at a risk status of Least Concern.  As in OHI global assessments, we scale the lower end of the goal to be 0 when 75% of species are extinct, a level comparable to the five documented mass extinctionsXXX66XXX and would constitute a catastrophic loss of biodiversity.  As calculated in our model, this corresponds to an average species extinction risk near Critically Endangered across all species.

