### Goal Description

Tourism and recreation in coastal areas is a major component of thriving coastal communities and a measure of how much people value ocean systems, i.e. by traveling to coastal and ocean areas. This goal aims to capture the number of people, and the quality of their experience, visiting coastal and marine areas and attractions. A score of 100 means a region utilizes its full recreational potential without harming the ecosystem.

### Model & Data 

For this goal, we use visitations to coastal parks and visitor centers as a measure of tourist activity.  Our area of "coastal interest" is defined here by a buffer extending 15 km inland.  To account for shifts in tourism due to special circumstances (e.g. 2010 Winter Olympics in Vancouver), we adjust regional visitations (coastal parks/visitors centers only) by the total visitations province-wide (including inland parks/visitors centers).


### Reference points 

We apply a temporal reference point, comparing current visitors (adjusted for province-wide visitations) to maximum observed visitors (again, adjusted) across each OHIBC region.  Visitors center visits are scored separately from park visits, and the two scores are averaged for the final TR status.





